## Advantages of deep learning framework
- More power than Numpy
- Tailored for deep learning, such as, automatic computation of gradients
- Easy incorporation with GPUs

### Tutorials
 - https://pytorch.org/tutorials/
 - https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

In [1]:
import torch
import numpy as np

## Basic data structure of pytorch is tensors (Similar to numpy arrays)

### Random initialization

In [2]:
x = torch.rand(2,2)

In [3]:
print(type(x))

<class 'torch.Tensor'>


In [4]:
print(x)

tensor([[0.3380, 0.1441],
        [0.6762, 0.8765]])


### Converting python list into pytorch tensor

In [5]:
x = torch.tensor([[2,2],[2,2]])

In [6]:
print (x)

tensor([[2, 2],
        [2, 2]])


### Converting numpy array into pytorch tensor

In [7]:
nx = np.array([[2,2],[2,2]])
x = torch.tensor(nx)
print (x)

tensor([[2, 2],
        [2, 2]])


### Properties of tensors

In [8]:
x = torch.rand([2,4,3])

In [9]:
x

tensor([[[0.0407, 0.7637, 0.1371],
         [0.4546, 0.7626, 0.7388],
         [0.0595, 0.0075, 0.2518],
         [0.9658, 0.7877, 0.9041]],

        [[0.7016, 0.3148, 0.1769],
         [0.9412, 0.0782, 0.3559],
         [0.5582, 0.5080, 0.7116],
         [0.9596, 0.2432, 0.6237]]])

In [10]:
x.shape

torch.Size([2, 4, 3])

#### Reshaping

In [11]:
x.view(24)

tensor([0.0407, 0.7637, 0.1371, 0.4546, 0.7626, 0.7388, 0.0595, 0.0075, 0.2518,
        0.9658, 0.7877, 0.9041, 0.7016, 0.3148, 0.1769, 0.9412, 0.0782, 0.3559,
        0.5582, 0.5080, 0.7116, 0.9596, 0.2432, 0.6237])

In [12]:
x.view([8,3])

tensor([[0.0407, 0.7637, 0.1371],
        [0.4546, 0.7626, 0.7388],
        [0.0595, 0.0075, 0.2518],
        [0.9658, 0.7877, 0.9041],
        [0.7016, 0.3148, 0.1769],
        [0.9412, 0.0782, 0.3559],
        [0.5582, 0.5080, 0.7116],
        [0.9596, 0.2432, 0.6237]])

In [13]:
x.view([2,12])

tensor([[0.0407, 0.7637, 0.1371, 0.4546, 0.7626, 0.7388, 0.0595, 0.0075, 0.2518,
         0.9658, 0.7877, 0.9041],
        [0.7016, 0.3148, 0.1769, 0.9412, 0.0782, 0.3559, 0.5582, 0.5080, 0.7116,
         0.9596, 0.2432, 0.6237]])

In [14]:
x.view([6,4])

tensor([[0.0407, 0.7637, 0.1371, 0.4546],
        [0.7626, 0.7388, 0.0595, 0.0075],
        [0.2518, 0.9658, 0.7877, 0.9041],
        [0.7016, 0.3148, 0.1769, 0.9412],
        [0.0782, 0.3559, 0.5582, 0.5080],
        [0.7116, 0.9596, 0.2432, 0.6237]])

### Slicing

In [15]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
x[0]

tensor([1, 2, 3])

In [18]:
x[0,:]

tensor([1, 2, 3])

In [19]:
x[:,0]

tensor([1, 4, 7])

In [20]:
x[:2,:]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
x[1:,]

tensor([[4, 5, 6],
        [7, 8, 9]])

In [22]:
x[:,1:2]

tensor([[2],
        [5],
        [8]])

### Derivatives

In [23]:
x=torch.tensor(3.0,requires_grad=True)

In [24]:
x

tensor(3., requires_grad=True)

In [25]:
y=x**2

In [26]:
y

tensor(9., grad_fn=<PowBackward0>)

In [27]:
y.backward()

In [28]:
x.grad

tensor(6.)

In [35]:
x=torch.tensor(5.0,requires_grad=True)
y=torch.log(x)
y.backward()
x.grad

tensor(0.2000)

#### Sigmoid

In [36]:
x=torch.tensor(0.0,requires_grad=True)

In [37]:
y = torch.sigmoid(x)

In [38]:
y

tensor(0.5000, grad_fn=<SigmoidBackward>)

In [39]:
y.backward()

In [40]:
x.grad

tensor(0.2500)

#### tanh

In [41]:
y = torch.tanh(x)

In [42]:
y.backward()

In [43]:
y

tensor(0., grad_fn=<TanhBackward>)

In [79]:
x.grad